import type { Metadata } from "next";
import "./globals.css";
import { comfortaa } from "./fonts/fonts";
import { AppUtils } from "./context/utils";
import { AppRemoveBg } from "./context/remove-bg";

export const metadata: Metadata = {
  title: "APP IG",
  description: "Generated by app ig",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        cz-shortcut-listen="true"
        className={`${comfortaa.className}`}
      >
        <AppRemoveBg>
          <AppUtils>

            {children}
            {/* <Toaster /> */}
          </AppUtils>
        </AppRemoveBg>
      </body>
    </html >
  );
}
