import type { Metadata } from "next";
import "./globals.css";
import { comfortaa } from "./fonts/fonts";
import { AppUtils } from "./context/utils";
import { AppRemoveBg } from "./context/remove-bg";
import { PlanActive } from "./context/planActive";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Loomibg",
  description: "Generated by Loomibg",
  other: {
    "google-adsense-account": "ca-pub-3582978571424183",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="icon" href='/icon.png' />
      </head>
      <body
        cz-shortcut-listen="true"
        className={`${comfortaa.className}`}
      >
        <AppUtils>
          <PlanActive>
            <AppRemoveBg>

              {children}
              <Toaster />
            </AppRemoveBg>
          </PlanActive>
        </AppUtils>
      </body>
    </html >
  );
}
